### PR TITLE
Create Doomsayer.java to provide dialogue 

### PR DESCRIPTION
**Pull request by lgdolman**
Add NPC dialogue folder and add dialogue for the Lumbridge Doomsayer using wiki transcript

### CODE REVIEW

**Comment by lgdolman** [comment]
image
Works as intended when testing on Dev LGD test world.

**Review by lgdolman — COMMENTED** [review]
tab change

**Review by titandino — CHANGES_REQUESTED** [review]
Thanks for the contribution! Only change I'd request is to use the plugin system instead of NPCHandler. Eventually NPCHandler will be outright deleted anyways.

To do this, you can annotate Doomsayer with `@PluginEventHandler` and add an appropriate NPC click handler like this:

```
@PluginEventHandler
public class Doomsayer extends Conversation {

	public static NPCClickHandler doomsayerOps = new NPCClickHandler(new Object[] { 3777 }) {
		@Override
		public void handle(NPCClickEvent e) {
			switch(e.getOption()) {
			case "Talk-to" -> e.getPlayer().startConversation(new Doomsayer());
			}
		}
	};

	...your constructor code

}
```

**Review by lgdolman — COMMENTED** [review]
Actioned and tested

**Pull request closed without merging**
